### ISSUE TITLE
struct Dav1dSettings error

### ISSUE THREAD

**Issue by ghost** [SDWebImage/libavif-Xcode#3]
When I updated to 0.10.1, there was a compilation error.
<img width="2121" alt="截屏2022-07-18 21 01 05" src="https://user-images.githubusercontent.com/17174309/179517241-5f268e3b-b814-4ea9-a4ec-ee8c8562ab8f.png">

**Comment by dreampiggy** [comment]
CococaPods ?
That `DAV1D_API_VERSION_MAJOR` macro is generated by CMake, maybe the prepare_command is not correct.

**Comment by dreampiggy** [comment]
Fixed and re-release libdav1d v1.0.0

https://raw.githubusercontent.com/CocoaPods/Specs/695c5afcbb03e14cef90b1d05f077fb7dee66abb/Specs/b/2/b/libdav1d/1.0.0/libdav1d.podspec.json

You may need 10~15 minutes to wait for CocoaPods trunk CDN to refresh the etag

And, if you already download this wrong version, purge your local cache:

```
rm -rf ~/.cocoapods/repos/trunk/Specs/
```

**Comment by ghost** [comment]
it‘s ok. thanks
